### ISSUE TITLE
Use yarn instead of npm

### ISSUE THREAD

**Issue by LeandroBariani** [zilpay/zilpay.xyz#11]
When compiling the code, it does not work using npm. This way you use yarn which will run very well.

**Comment by hicaru** [comment]
hello, did you run `npm run build`?

**Comment by LeandroBariani** [comment]
Hi. Actually, I was able to boot the system with 'npm run build' then 'npm run start', and it worked very well. Thank you. I believe I had an outdated version of npm, so it didn't start.
Note: I was starting the system with the command 'yarn run dev'.

**Comment by hicaru** [comment]
yeah, for it need just add `yarn config`
