### ISSUE TITLE
Account inacessible after failed transaction

### ISSUE THREAD

**Issue by Googooboyy** [zilpay/zilpay.xyz#12]
On 31st Jan 2021, I made a transaction on ZilSwap.io. 

A few minutes later, it failed. [trx HASH](https://viewblock.io/zilliqa/tx/0x0b5d56be46b4a70f89a96d303e6622e207407fb731e1bac42c69acc5ef4b5b9e)

Today I am still unable to make any transaction or connect my wallet to Zilswap.io or Stake.Zilliqa.Com.

So I removed the extension and reinstalled it.

Tried to log back into my account and I am getting a seed phrase error (and I know it's not wrong, because I have the same account on multiple other computers).

**Comment by hicaru** [comment]
Hello this transaction is correct. Fail in the contract code https://viewblock.io/zilliqa/address/zil1hgg7k77vpgpwj3av7q7vv5dl4uvunmqqjzpv2w?tab=code

**Comment by Googooboyy** [comment]
Thank you Hicaru. Does this mean that the ZilSwap contract code (not ZilPay) is the one with the issue?

**Comment by hicaru** [comment]
yes

**Comment by Googooboyy** [comment]
Issue seems to be over, organically. Might have something to do with the network not progressing fully on 2nd Feb and 3rd Feb.
